export const POST_ACTION = {
    ADD_POST: "ADD_POST",
    UPDATE_POST: "UPDATE_POST",
    DELETE_POST: "DELETE_POST"
}

export const BOOK_ACTION = {
    ADD_BOOK: "ADD_BOOK",
    UPDATE_BOOK: "UPDATE_BOOK",
    DELETE_BOOK: "DELETE_BOOK"
}